### ISSUE TITLE
citra needed to create sdmc://3ds/dspfirm.cdc to run LovePotion

### ISSUE THREAD

**Issue by ajmaidak** [TurtleP/LovePotion#102]
### **Describe the bug**
citra needed to create sdmc://3ds/dspfirm.cdc to run LovePotion

### **Expected behavior**
Shouldn't need to create this file in citra.

I'm not expecting this bug to be fixed.  I'm really just logging it here because it took me a long time to figure this out and the issue doc may help others.

### **Relevant Code To Reproduce**
- Install citra, 
- build LovePotion at commit 239e36941b46dd2faa6ca580081d7f2012896b9b
- Place a trivial main.lua in sdmc://game
- Run the LovePotion.3dsx in citra it will startup and immediately exit

Error in the crash.txt will be 
```
Error: Failed to load ndsp. Please make sure your dspfirm.cdc has been dumped properly.
stack traceback:
	[string "boot.lua"]:495: in function <[string "boot.lua"]:490>
	[C]: ?
	[C]: in function 'require'
	[string "boot.lua"]:388: in function <[string "boot.lua"]:285>
	[C]: in function 'xpcall'
	[string "boot.lua"]:506: in function <[string "boot.lua"]:498>
	[C]: in function 'xpcall'
```

I had to create a zero byte `sdmc://3ds/dspfirm.cdc` to run the game successfully.

### **System Info [Please complete the following information]:**
 - System: citra, Nightly 1465
 - Löve Potion version: 239e36941b46dd2faa6ca580081d7f2012896b9b

**Comment by TurtleP** [comment]
As you've mentioned, this isn't a bug that can be fixed. It was done intentionally. If memory serves it *should* have actually shown the typical error handler. Either way, using emulation isn't the best solution to testing, but I do understand that not everyone has the hardware nor patience to debug back and forth.

Aside from this, you can always test via LOVE itself--Love Potion is mostly compatible with the desktop counterpart. The 3DS version specifically has some differences, but I hope that this makes sense and I'm not coming off as rude.

Lastly, please don't build from source. There's a (Pre)Release I made yesterday which would suit you better as it has several fixes since the commit you've mentioned.

You can also join the Discord (follow the link to the Wiki from the (Pre)Release page) for future help as well.
