### ISSUE TITLE
[BUG] love.system.getOS Exception

### ISSUE THREAD

**Issue by Pienkaito** [TurtleP/LovePotion#103]
Calling love.system.getOS() returns an exception. This worked on previous versions.
How I called it:
```
if love.system.getOS() == 'Horizon' then	
  --do stuff
end
```
Error:
```
Error: ./main.lua:31: attempt to index field 'system' (a nil value)
stack traceback:
	[string "boot.lua"]:495: in function <[string "boot.lua"]:490>
	./main.lua:31: in function 'load'
	[string "boot.lua"]:434: in function <[string "boot.lua"]:432>
	[C]: in function 'xpcall'
	[string "boot.lua"]:522: in function <[string "boot.lua"]:498>
	[C]: in function 'xpcall'
```
This happens with the latest 2.0.0 Pre-release 1

System: Switch
FW: 9.0.1
CFW: AMS 0.10.5
https://github.com/TurtleP/LovePotion/tree/2.0.0-pre1

**Comment by TurtleP** [comment]
I seem to have forgotten to mention in the gist notes that `love._os` can be used to get this. However, I have not added the `system` module just yet which is why you see this error.

You can also use `love._console_name` to detect the current running console. Note that both of these are just variables and not functions.

**Comment by TurtleP** [comment]
not sure why i closed it.. reopening to remind myself

**Comment by TurtleP** [comment]
commit 89d1889 implements the system module :)

I expect to get Pre-Release 2 out on Monday
