### ISSUE TITLE
Doesnt work on 5.0.X

### ISSUE THREAD

**Issue by swoozi** [TurtleP/LovePotion#22]
I just tested and crashed.

**Comment by TurtleP** [comment]
this is a known issue, and I'm afraid we can't do too much about it until libnx properly supports 5.x firmwares. 4.x and lower work better. I'll keep this open since it *is* valid, but also so that others with this issue can see that it's known.

like @notquiteapex said, if there's an error code or anything we can use to relay to the libnx developers, it would be super useful.

**Comment by TurtleP** [comment]
@swoozi should be fixed with 1.0.1 :)
