### ISSUE TITLE
Add support for hbmenu config

### ISSUE THREAD

**Issue by TurtleP** [TurtleP/LovePotion#47]
Would be useful mainly because users wouldn’t have to compile an entire nro every time. File association of a romfs with a *.love extension should work (passed via args). 

See [this page](https://switchbrew.org/wiki/Homebrew_Menu#File_Associations) for details

**Comment by NotQuiteApex** [comment]
I agree having a RomFS archive (called `game.romfs`? using a .love extension could cause confusion) would be a nice feature. The ability to load `.zip`'s and `.love`'s would also be nice.

I still think these methods are still more difficult and time consuming for other users than just using a game folder. I understand the argument that the game folder can become cluttered by users just continuously dropping edited and new files from their projects via FTPD, but the game folder should really be mainly used for testing, rather than full releases of a project. A full release should compile the latest Löve Potion `.elf` with RomFS.

an hierarchy of which format is chosen at runtime should be rather simple:
* internal RomFS
* `.romfs` file
* `game.love` file (if added)
* `game.zip` file (if added)
* `game` folder (if added back)
* no game

**Comment by TurtleP** [comment]
It's not so much that the game folder would be cluttered, but either the sd card itself or at worst case, overwriting someone else's files. I'm sure people would be able to keep the proper folder structure, but there's also cases where some may just plop contents wherever they want. I want it to be painless so they don't accidentally mess up someone else's project files. Especially going forward with the argv stuff, people can just plop their RomFS anywhere and run it through Love Potion when they "select" that RomFS. Hopefully that all makes sense.

I kind of wish it were easier to bring back the `game` directory.. though if possible.. we could have `{game}`.lp as a folder and .. I'm not sure if that would even work for file associations, given that's a directory. I'll poke some people about that one.

- Internal RomFS would be default, unless argv were populated with an associated file type
    - At this point with argv populated, use *that* RomFS, as long as we verify it is one.
- Fallback to `no game`

Remember, *.love files are just renamed zips, so technically we could make the associated files as `{game}.love` while verifying them as being RomFS. While at the same time, you can think of a RomFS as something *like* a zip file itself, but it really isn't.

**Comment by NotQuiteApex** [comment]
Shouldn't be too hard to do that.

My main concern is that most people see a `.love` as a `.zip`, rather than just any archive containing a LOVE2D game, which could lead to confusion. `.lpnx` would work for NX RomFS archives, if the distinction needed to ever be made between 3DS and Switch RomFS archives should the 3DS HBLauncher ever get file association stuff (`.lp3ds`?).

I think allowing for `.zip`(`.love`) as possible associated types would help solve that overwriting problem, since the zip would clearly be named and adding to zip archives isn't as simple as directories (on FTPD at least). _Although I do admit it could be a lot of work._

**Comment by TurtleP** [comment]
There was one thing we never discussed about this. Where would we save data? Löve Potion by default saves files in the current working directory of where it was launched. This should suffice as long as it sees the cwd as where the launched RomFS is. Also, I would agree to `game.lpnx` as the archive naming convention.

Another thought: I know LOVE doesn't do this, but should we have a notice for newer versions of LOVE being found on GitHub in the future? The switch can't do SSL just yet™, but it may prove useful. I'd imagine on boot to check for updates and show an update message (but only if it's the first launch of the day kind of thing--but this may get annoying or repetitive, so I'm not sure)

**Comment by NotQuiteApex** [comment]
That would keep savefiles simple, yeah. As for the newer versions, I think the checks should only be done on non-fused games. That way games that are binary files finished for proper release don't nag users about how the programmer isn't on the latest release.

**Comment by TurtleP** [comment]
this would be super useful, yeah, especially using the `t.release` conf flag that LOVE already supports

**Comment by TurtleP** [comment]
Fixed with the latest commit
