### ISSUE TITLE
[TO DO] Multi-platform multithreading

### ISSUE THREAD

**Issue by NotQuiteApex** [TurtleP/LovePotion#91]
The code for Switch multithreading is already in place, and the love.thread module is currently stubbed. Most of the function names are identical across libctru and libnx, any that aren't can be swapped with preprocessor directives.

Threads will be an amazing improvement for 3DS, which completely locks up during the boot sequence. In theory, tests done on either system should indicate that both systems will work fine if the code is identical in function.

**Comment by TurtleP** [comment]
When has 3DS ever locked up during the boot sequence though? I mean it *used* to, but that was back in the day when you loaded large audio files. I haven't had any lockup issues (and the tests yesterday for the deferring were not lock ups--we just didn't set the default font :P). Furthermore, boot can lockup if we don't initialize the modules in proper order (which was also fixed when we were testing your deferrral branch).

I'll look into seeing whether 3DS SDL1.2 threads work since that would help cross-platform use.

**Comment by NotQuiteApex** [comment]
It happens when loading files for games, like audio or image files. It can just happen when a lot of stuff is being done in love.load. Having threading would allow for faster loads with bigger projects.

**Comment by TurtleP** [comment]
Yeah, figured. I don't think desktop LÖVE even uses a spinoff thread to run `love.load`. Essentially that whole debacle would be on the end-user to do.

**Comment by TurtleP** [comment]
Hopefully we can get multithreading done properly now with the rewrite. Would it be alright if I delete the relevant branch, @NotQuiteApex?

**Comment by NotQuiteApex** [comment]
Sounds good.

**Comment by TurtleP** [comment]
Done.
