### ISSUE TITLE
[Request] Loading images without conversion to T3X

### ISSUE THREAD

**Issue by ctr-del** [TurtleP/LovePotion#95]
I believe the old version (Pre-TurtleP fork) of LövePotion did this and it's noticably absent in this version, at least to my knowledge.

When I try to load a *.png image, it throws an error telling me the image doesn't exist. According to the error screen, it appears that it's looking for t3x files and only t3x files. Would it be possible to load image files without converting to t3x first?

**Comment by TurtleP** [comment]
Yeah, it used to be like that. Unfortunately it seemed to cause some issues, especially while using citro2d. We had to switch to using t3x files since the library natively uses the format. Honesty I would love to be able to use png files as well, but it’s counterproductive with this library.

That said, please take a [look at the wiki](https://TurtleP.github.io/LovePotion/wiki) for details in regards to the proper 3ds game building templates if you have not done so.
